# Generated by Django 5.2.7 on 2025-10-08 18:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('studio', 'Studio'), ('duplex', 'Duplex')], max_length=20)),
                ('furnishing', models.CharField(choices=[('furnished', 'Furnished'), ('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi-Furnished')], default='unfurnished', max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bedrooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('square_feet', models.PositiveIntegerField(blank=True, null=True)),
                ('floor_number', models.PositiveIntegerField(blank=True, null=True)),
                ('total_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utilities_included', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_garden', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_elevator', models.BooleanField(default=False)),
                ('has_air_conditioning', models.BooleanField(default=False)),
                ('has_heating', models.BooleanField(default=False)),
                ('has_washer_dryer', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='available', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('available_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
