# Generated by Django 5.2.7 on 2025-10-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default='unknown location', max_length=255),
        ),
    ]
