# Generated by Django 5.2.7 on 2025-10-08 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('move_in_date', models.DateField()),
                ('lease_duration_months', models.PositiveIntegerField(default=12)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=50)),
                ('employer_name', models.CharField(blank=True, max_length=100)),
                ('employer_phone', models.CharField(blank=True, max_length=20)),
                ('reference1_name', models.CharField(blank=True, max_length=100)),
                ('reference1_phone', models.CharField(blank=True, max_length=20)),
                ('reference1_relationship', models.CharField(blank=True, max_length=50)),
                ('reference2_name', models.CharField(blank=True, max_length=100)),
                ('reference2_phone', models.CharField(blank=True, max_length=20)),
                ('reference2_relationship', models.CharField(blank=True, max_length=50)),
                ('has_pets', models.BooleanField(default=False)),
                ('pet_details', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_applications', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='properties.property')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('property', 'applicant')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_from_owner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='applications.rentalapplication')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id', 'Government ID'), ('pay_stub', 'Pay Stub'), ('bank_statement', 'Bank Statement'), ('employment_letter', 'Employment Letter'), ('reference_letter', 'Reference Letter'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='application_documents/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.rentalapplication')),
            ],
        ),
    ]
