# Generated by Django 5.2.7 on 2025-10-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapplication',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
